### ISSUE TITLE
Idea: add a “file explorer” to easily browse repos from ash-nazg's UI?

### ISSUE THREAD

**Issue by tripu** [w3c/ash-nazg#11]
Suggested by @deniak; cf [&ldquo;Create a GitHub File Explorer Using Vue.js&rdquo;](https://scotch.io/tutorials/create-a-github-file-explorer-using-vue-js).

(I'm not sure yet about the real value of such a feature; unless we augment GitHub's interface with more features related to ash-nazg's goals, a link to the repo would do instead?)

**Comment by dontcallmedom** [comment]
I'm not sure this is in scope for ash-nazg, so closing
