### ISSUE TITLE
Device and Sensors WG?

### ISSUE THREAD

**Issue by plehegar** [w3c/ash-nazg#129]
In https://labs.w3.org/hatchery/repo-manager/admin/groups
 we have a Device and Sensors Working Group

but in
  https://labs.w3.org/hatchery/repo-manager/repo/import
 it doesn't appear. (or appear as Device APIs?)

**Comment by dontcallmedom** [comment]
I've updated the name from Device APIs to Devices and Sensors.

see #124 for the broader issue
