### ISSUE TITLE
Improve error handling of unconnected accounts

### ISSUE THREAD

**Issue by wseltzer** [w3c/ash-nazg#130]
for an unknown contributor, the error page offers "@@ is unknown, they need to link their Github account with a W3C account." but the links are directed to the viewer's account, not the third-party who made the PR, namely https://www.w3.org/users/myprofile/connectedaccounts

instead or in addition, it would be helpful to link the submitter's GH profile so team reviewers can assess whether or not the person should be able to make substantive contributions.

**Comment by dontcallmedom** [comment]
if I understand the first suggestion right, we can't put a link to the submitter's account, since by definition at that stage, we don't know which account they have (nor if they have one).

I have added a link to the GH's profile.
