### ISSUE TITLE
APA WG is missing

### ISSUE THREAD

**Issue by plehegar** [w3c/ash-nazg#141]
Accessible Platform Architectures (APA) Working Group is missing from the list of Working Groups. Personalization Semantics was added to their charter recently. So w3c/personalization-semantics will need to be moved to APA.

**Comment by dontcallmedom** [comment]
as mentioned in #138, groups have to be enabled via the admin interface (to which you should have access) - please do not open bugs for this (meanwhile, I have enabled APA)

**Comment by plehegar** [comment]
oops. sorry for the noise. will try to remember.
