### ISSUE TITLE
login problems, glitchy

### ISSUE THREAD

**Issue by wseltzer** [w3c/ash-nazg#146]
From some pages, the login link gets extra directories, e.g. from a page on which I was trying to re-validate a contribution, I ended up at  https://labs.w3.org/repo-manager/hatchery/repo-manager/repo-manager/login 

Can't reproduce now, however.

**Comment by dontcallmedom** [comment]
I think that's a dup of #91

**Comment by wseltzer** [comment]
ack, closing this one
