### ISSUE TITLE
Archiving notification requests

### ISSUE THREAD

**Issue by plehegar** [w3c/ash-nazg#149]
ash-nazg only notify [team contacts](https://github.com/w3c/ash-nazg/blob/master/notification.js#L14)  in case of external contributions Can we also cc some archive, to maintain some historical records? @wseltzer , should the archive be team, member, or public?

**Comment by wseltzer** [comment]
Let's start by making a team-visible archive, and see what that looks like. Thanks.

**Comment by dontcallmedom** [comment]
The sent messages to team contacts (when their email addresses are available on github) and messages sent to external contributors (when their email addresses are available on github)  are already copied to the team-only archive mailing list.

So, unless I misunderstood the request, I believe this is already in place.

**Comment by wseltzer** [comment]
The request is for a single mailing list to collect all the messages sent by ash-nazg flagging IPR issues. Searching the team archive, I'm not seeing them all (unless that archiving was itself added only recently).

**Comment by dontcallmedom** [comment]
the archiving went down for a few weeks (November & December IIRC) due to a bug when the system was migrated from one server to another.

But otherwise, every mail that was sent should have been archived.
