### ISSUE TITLE
Failure page doesn't provide any indication as to how to make IPR commitments

### ISSUE THREAD

**Issue by gsnedders** [w3c/ash-nazg#150]
e.g., https://labs.w3.org/repo-manager/pr/id/w3c/webdriver/1399 says "gsnedders did not make IPR commitments for this group", but there's no link or anything telling me where or how I can make IPR commitments for that group.

**Comment by craigfrancis** [comment]
I was told that I could join by going to: https://www.w3.org/community/wicg/participants

So the pull request just adds a "join" link that might help.

**Comment by yoavweiss** [comment]
The thing is, the group in question will vary based on the group responsible for the repo. @dontcallmedom - is that something that the repo-manager is aware of and can vary the link based on?
