### ISSUE TITLE
Can't associate repo with WG

### ISSUE THREAD

**Issue by wseltzer** [w3c/ash-nazg#158]
Trying to add a repository for WebAppSec (or to add the right files to w3c/webappsec-fetch-metadata, which I imported manually before rediscovering this tool), but all the WGs are greyed out on https://labs.w3.org/repo-manager/repo/import

**Comment by dontcallmedom** [comment]
you need to un-select the current community group before you can select a working group (since a repo can't be associated to both a CG and a WG at this time); I've imported the repo in the meantime.

**Comment by wseltzer** [comment]
thanks @dontcallmedom . I didn't think a CG was selected
