### ISSUE TITLE
The acronym or term "IPR" is not clearly defined

### ISSUE THREAD

**Issue by guest271314** [w3c/ash-nazg#160]
> Questions or comments? Please let us know on the GitHub Repo for ash-nazg.

The acronym or term "IPR" and is not clearly defined at the README.md or any substantive linked document, e.g., what exactly is an "IPR commitment" at https://labs.w3.org/repo-manager/pr/id/w3c/mediacapture-screen-share/109 ? 

Does that acronym refer to "Intellectual Property Rights"? Or does the term "IPR" and "IPR commitment" as applied in W3C documents linked to this repository have a different meaning. Currently the answer is not clear.

**Comment by dontcallmedom** [comment]
@wseltzer can you suggest how best to represent this?

**Comment by wseltzer** [comment]
@dontcallmedom suggest s/IPR/patent and copyright/ as that's what we're asking for.

**Comment by guest271314** [comment]
https://github.com/guest271314/ash-nazg/pull/1/files/01687b9fc06a5cae53c2b2b06fde5c55dd270210..1cc0ec3041e619ca4b22b136d15a158d5884ad9e
