### ISSUE TITLE
Can I add a repo associated with an IG?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/ash-nazg#161]
Hi all,

I wanted to add a repo associated with the Web Payment Security IG. I added the group via the admin page for groups. It does not show up on the "new repo" page in the list of groups.

Thanks!

Ian

**Comment by dontcallmedom** [comment]
Hi Ian, the repo manager is only meant to be used for spec-producing groups (WGs and CGs) on spec-producing repos.

We know it is also being used to create repos from scratch with the proper structure, but the tool isn't yet adapted to that usage see #154
