### ISSUE TITLE
"Repository webhooks and services" should not be required

### ISSUE THREAD

**Issue by annevk** [w3c/ash-nazg#164]
I should not be required to give this tool write access to repositories (or any kind of access even) to mark something as non-substantive.

**Comment by dontcallmedom** [comment]
The reason it asks that access is because the tool then posts a comment on the issue under the name of the person who did the non-substantive assessment (to make that assessment part of the issue record).

I agree it doesn't feel ideal to ask for so much privilege - do you have a suggestion for an alternative behavior?

**Comment by annevk** [comment]
Two things come to mind:

1. If possible, scope the read/write access to organizations belonging to the W3C. Presumably that's non-controversial.
2. Give the bot access to all those organizations and make the bot comment with a link to the person who did the assessment (the link could be to their W3C profile if you don't trust GitHub usernames to be stable or some such).

**Comment by dontcallmedom** [comment]
Re 1, OAuth-based github auth has [very limited granularity](https://github.com/isaacs/github/issues/731) unfortunately.

I'll look into providing #2 - meanwhile, if you're stuck with marking a PR as non-substantive, feel free to reach out to me.

**Comment by annevk** [comment]
Trying to login today I see:
<img width="473" alt="Screenshot 2020-10-27 at 09 35 16" src="https://user-images.githubusercontent.com/1544111/97276669-ce662280-1837-11eb-9040-dd08c7d29d80.png">
It seems this really shouldn't be required for a login.

**Comment by dontcallmedom** [comment]
@deniak any chance you could help with this? 

I think what we would need is to distinguish an admin login flow (the one we currently have) from a regular contributor flow (which would only validate that the person has a working github account we can reference in a comment posted on the relevant pull request when marking it as non-substantive).

**Comment by deniak** [comment]
> @deniak any chance you could help with this?
> 

Sure, I'll see what I can do.

**Comment by annevk** [comment]
Thanks for fixing this @deniak!
