### ISSUE TITLE
Cannot reauthorize PR

### ISSUE THREAD

**Issue by OR13** [w3c/ash-nazg#168]
https://github.com/w3c/did-core/pull/156

My accounts are linked.

After logging in it just says "Failed to fetch"

Console displays error:

```
https://labs.w3.org/repo-manager/api/team-contact-of net::ERR_HTTP2_SERVER_REFUSED_STREAM
```

**Comment by deniak** [comment]
I see the [repository managed to validate the PR](https://labs.w3.org/repo-manager/pr/id/w3c/did-core/156). I'm guessing it was a transient issue.

**Comment by dontcallmedom** [comment]
for clarity sake, I did the revalidation when I saw the error report - I couldn't determine then whether this was indeed a transient error (which the console message seems to hint towards) or something else.

**Comment by OR13** [comment]
Closing as transient issue.
