### ISSUE TITLE
Work jointly done by a CG & a WG

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/ash-nazg#181]
There are at least two reasonably clear cases of WGs that want to operate their repositories under the joint aegis of a WG and a CG: WebAssembly and WebGPU.

Right now, the IPR manager isn't able to handle this case, and requires joint work to be under groups of the same type (either several WGs, or several CGs).

A possible model for an IPR check on joint CG/WG work would be:
* if contributor is covered by WG IPR commitment, OK
* if contributor is covered by CG IPR commitment (but not WG), flag the need to obtain an [FSA commitment](https://www.w3.org/community/about/process/final/)
* otherwise, flag as needing action

@wseltzer thoughts?

**Comment by dontcallmedom** [comment]
cc @tidoust

**Comment by xfq** [comment]
(This may also be the case for MiniApps, if the WG is successfully established.)

**Comment by wseltzer** [comment]
We probably need to consider as distinct use cases: 
* Contribution to a WG deliverable
* Contribution to a CG deliverable (that may or may not be intended as eventual WG input)

**Comment by dontcallmedom** [comment]
my impression is that in WebAssembly land (and soon in WebGPU land) there may be CG-only items, but WG items are considered joint CG & WG - I could be wrong though.

(the model of clean split between CG & WG is what has been used in the Immersive Web context)

**Comment by tidoust** [comment]
> my impression is that in WebAssembly land (and soon in WebGPU land) there may be CG-only items, but WG items are considered joint CG & WG - I could be wrong though.

I confirm that this is the case for WebGPU. At least initially, the idea is for the specs to be shared between the CG and WG (same repo, same content).

**Comment by ianbjacobs** [comment]
Proposed: 

* When a repo is shared by a WG and a CG, we set it up so that it is owned by the WG. 
* This would mean that pull requests by WG participants would not require manual intervention, and all other pull requests would require intervention (e.g., "editorial", "please make the RF commitment").

**Comment by ianbjacobs** [comment]
Some other bits from discussion:

* If a repo is originally owned by a CG and is transferred to a WG, flip the bit upon transfer to make it a WG repo.
* It is preferred to use one repo per document.

**Comment by dontcallmedom** [comment]
no work needed in ash-nazg on this, closing the issue
