### ISSUE TITLE
Web Bluetooth CG is missing

### ISSUE THREAD

**Issue by reillyeon** [w3c/ash-nazg#185]
According to #141 the ability to add a WG/CG is part of the admin interface which I appear not to have access to. Please add the Web Bluetooth CG.

**Comment by yoavweiss** [comment]
Done!

**Comment by dontcallmedom** [comment]
@reillyeon if you need help plugging https://github.com/webbluetoothcg/web-bluetooth into the repo IPR manager, I'll be happy to give a hand as needed.

I can't do the import itself at the moment since that requires admin right on the repo which I don't have.
