### ISSUE TITLE
IPR validation failed after previously passing

### ISSUE THREAD

**Issue by chcunningham** [w3c/ash-nazg#188]
For this PR, I see the validation passed for my first commit, but failed for my second
https://github.com/WICG/web-codecs/pull/109/commits

The user should be identical and I haven't (to my knowledge) changed any settings or group memberships.

**Comment by dontcallmedom** [comment]
this was a temporary failure due to issues with the W3C API which is used under the hood

**Comment by chcunningham** [comment]
Shoud IPR checks now go green if I simply click "revalidate"? They seem to still fail. 
https://labs.w3.org/repo-manager/pr/id/WICG/web-codecs/112

**Comment by chcunningham** [comment]
Huh, as soon as I posted that it went green. Pls ignore.

**Comment by dontcallmedom** [comment]
not your fault, the "revalidate" flow has a bug where it doesn't show the correct result

**Comment by dontcallmedom** [comment]
(filed in #191)
