### ISSUE TITLE
IPR checks fail but should pass

### ISSUE THREAD

**Issue by afs** [w3c/ash-nazg#189]
See https://labs.w3.org/repo-manager/pr/id/w3c/rdf-star/56

I have checked sign-up to RDF-DEV and I see that the account @afs primary email address is listed as a Apache Software Foundation participant. (I am the W3C AC rep for ASF.)

**Comment by afs** [comment]
https://github.com/w3c/rdf-star/pull/52 -- the IPR test passed, same setup on 5/Dec.

**Comment by afs** [comment]
Maybe nothing but two repos w3c/rdf-star and w3c/rdf-start in the groups database : https://labs.w3.org/repo-manager/repos and "rdf-start" seems not to exist.

**Comment by dontcallmedom** [comment]
this was a temporary failure due to issues with the W3C API which is used under the hood
