### ISSUE TITLE
IPR checks now failing

### ISSUE THREAD

**Issue by svgeesus** [w3c/ash-nazg#190]
A [longtime member](https://github.com/fantasai/) of the CSS WG had a [pull request](https://github.com/w3c/csswg-drafts/pull/5761) fail due to [IPR check](https://labs.w3.org/repo-manager/pr/id/w3c/csswg-drafts/5761) which asks for her to join the WG, or make a non-participant commitment.. 

She has [been a member for years](https://www.w3.org/groups/wg/css/participants).

This regression seems to have happened in the last 24 hours.

**Comment by dontcallmedom** [comment]
this was a temporary failure due to issues with the W3C API which is used under the hood
