### ISSUE TITLE
Non-participation contribution created even if the contributors haven't linked their accounts

### ISSUE THREAD

**Issue by deniak** [w3c/ash-nazg#192]
The form allows a team contact to create the non-participant contribution for a PR without having the contributor link their W3C account. This should not be possible as it's one of the requirement from the non-participant system.

**Comment by iherman** [comment]
If possible... the staff contact should be warned if he/she tries to do that so that he/she would contact the contributor.

Ideally, the system could also send a comment on the PR telling the contributor to do that extra step without the intervention of the staff contact.
