### ISSUE TITLE
More detailed instructions for non-participants

### ISSUE THREAD

**Issue by samuelweiler** [w3c/ash-nazg#198]
The repo manager directs non-members to talk to team contacts to make IPR commitments.  (See the last bullet on https://labs.w3.org/repo-manager/pr/id/w3c/webappsec-csp/457)

Rather than refer non-participants to team contacts, who then have to remember where everything is, could we instead provide the step-by-step on the repo manager page?  Here's an example of the step-by-step: 
https://github.com/w3c/webappsec-csp/pull/457#issuecomment-765682952

**Comment by dontcallmedom** [comment]
I don't believe the instructions you provided in https://github.com/w3c/webappsec-csp/pull/457#issuecomment-765682952 are correct - our current mechanism to obtain a non-participant licensing commitment requires specific action from the staff contact, it can't be obtained on its own by the participant.
