### ISSUE TITLE
Many IPR failing checks

### ISSUE THREAD

**Issue by csharrison** [w3c/ash-nazg#201]
All of a sudden I am seeing IPR failing checks for myself a number of other Chrome engineers.
e.g. https://labs.w3.org/repo-manager/pr/id/WICG/conversion-measurement-api/143

**Comment by pchampin** [comment]
Got a similar proplem of the RDF-star repository:
https://labs.w3.org/repo-manager/pr/id/w3c/rdf-star/162

In my case, I though the problem came from me having two W3C accounts (although this had not caused any problem before), but joining the CG with my 2nd account didn't solve the problem.

**Comment by deniak** [comment]
There was a bug with the W3C API that broke how the repository manager retrieves the user's group participations. I temporarily reverted the update on the API.
For all the PR created between Thursday and Friday, if the repository manager reports a failure, try to hit the 'revalidate' button. I just did so for the 2 PRs above and the check now pass.

**Comment by dontcallmedom** [comment]
I believe the problem has now been solved by @deniak closing the issue
