### ISSUE TITLE
PR from taken-over repo should have IPR issues

### ISSUE THREAD

**Issue by fgmccabe** [w3c/ash-nazg#208]
Please see https://github.com/w3c/webappsec-csp/pull/293. This repo & PR was originally created by eholk. I took it over because he left Google and stopped working on this topic. I am trying to keep the PR because of its comment history.

The complaint should be either removed or redirected to me. However, I believe that I am already a contributor to this effort.

Thanks for your attention
Francis McCabe

**Comment by dontcallmedom** [comment]
fixed with https://github.com/w3c/webappsec-csp/pull/293#issuecomment-878402505
