### ISSUE TITLE
Metaverse Interoperability Community Group missing from list

### ISSUE THREAD

**Issue by robertlong** [w3c/ash-nazg#209]
I'm trying to import a [repository](https://github.com/omigroup/gltf-extensions) in to the repo manager, but our community group isn't on the list of groups. Could add the [metaverse-interop](https://www.w3.org/community/metaverse-interop/) community group? I'm trying to add the IPR bot, w3c.json, etc. Thanks!

**Comment by dontcallmedom** [comment]
group now added - let us know if you encounter any other hiccup in the process

**Comment by robertlong** [comment]
It works, thanks!
