### ISSUE TITLE
Guidance on non-participant licensing commitments

### ISSUE THREAD

**Issue by nitedog** [w3c/ash-nazg#216]
When Pull Requests are made by non-participants, the staff contact is asked to validate it. One of the option says:

> Otherwise, the WG’s team contacts will request the contributors to sign the non-participant licensing commitments

Issue: I don't know how to ask the contributor to sign the non-participant licensing commitments.

Suggestion: Add a link to further guidance or a link to the form that needs to be signed.

**Comment by deniak** [comment]
The description is not clear enough. I'll update it but in order to ask the person for the non-participant licensing commitments, the repository manager needs the contributor to get a W3C account and link it to their GH account.
Once the account is set up, a new link should appear to the team contact so they can request the commitment.

**Comment by deniak** [comment]
@nitedog can you point me to the PR you are trying to validate?

**Comment by nitedog** [comment]
https://github.com/w3c/wcag-act/pull/520

**Comment by deniak** [comment]
@nitedog, you should now see a link 'Ask for non-participant commitment' at the top of https://labs.w3.org/repo-manager/pr/id/w3c/wcag-act/520. This will lead you to a form to request the commitment.

**Comment by nitedog** [comment]
It now says:

> carlosapaduarte did not make IPR commitments for this group. To make the IPR commitments, carlosapaduarte should join the Accessibility Guidelines Working Group.

There is no form to request the commitment, only to join the group.

**Comment by deniak** [comment]
The form is actually only available to team contacts and I just realize there's a bug in the way we detect the team contacts. I'm working on a fix.

**Comment by deniak** [comment]
@nitedog, you should now see the link to the form on https://labs.w3.org/repo-manager/pr/id/w3c/wcag-act/520

**Comment by nitedog** [comment]
No, it still says the same as [above](#issuecomment-914141971) (contributor needs to join the working group).

**Comment by deniak** [comment]
I discussed the issue with @nitedog on IRC and he was not logged in the repo manager. After authenticating, he managed to request the commitment.
