### ISSUE TITLE
Rename WICG/ScrollToTextFragment to WICG/scroll-to-text-fragment

### ISSUE THREAD

**Issue by bokand** [w3c/ash-nazg#231]
The repo was renamed long ago to match WICG naming style but it looks like the IPR bot is still looking for the old name at https://labs.w3.org/repo-manager/repos which is causing failed checks on pull requests. Would appreciate guidance/help, thanks!

**Comment by deniak** [comment]
Hi,

The repository manager doesn't support repository renaming yet. I've updated the name manually so the problem should be fixed for your repository.
Are you able to redeliver the webhook payload for the 2 pending PRs https://github.com/WICG/scroll-to-text-fragment/pull/175 and https://github.com/WICG/scroll-to-text-fragment/pull/176? If you aren't sure how to do this, I'm happy to help but I'll need admin rights to the repository to get access to the webhook.

**Comment by bokand** [comment]
I think I figured it out. At least, I got the IPR success check on those PRs so I think it worked?

Thanks for the help!
