### ISSUE TITLE
What is a "known secret"?

### ISSUE THREAD

**Issue by svgeesus** [w3c/ash-nazg#232]
I'm getting an [odd error]https://labs.w3.org/repo-manager/pr/id/w3c/IFT/47) "PR not found: w3c/IFT/pulls/47"

And on [the PR itself](https://github.com/w3c/IFT/pull/47) it says 

> GitHub signature does not match known secret for w3c/IFT. 

The contributor is a WG Member so there should be no issue, and we don't get this error with other repos like CSSWG.

**Comment by deniak** [comment]
I've re-triggered the webhook for that PR and it now passes.
Looking at the logs, I see you re-imported the repository today which could explain why it's working now.

**Comment by svgeesus** [comment]
I did re-import it, but that didn't seem to have any effect. Maybe it takes effect after a while?

**Comment by svgeesus** [comment]
Happy that it works now :)
