### ISSUE TITLE
Add WinterCG to groups list

### ISSUE THREAD

**Issue by lucacasonato** [w3c/ash-nazg#245]
Hey folks :wave: 

We'd like to use repo manager for the [WinterCG](https://www.w3.org/community/wintercg/) group (repos in https://github.com/wintercg). Could you add the CG to the list of allowed groups for repo manager?

Thanks!

**Comment by deniak** [comment]
@lucacasonato you should be able to [import a repository](https://labs.w3.org/repo-manager/repo/import) as long as you are one of the owners of the wintercg GitHub organization. The [README](https://github.com/w3c/ash-nazg#new-repository) provides some details on how to do the import/create.
Also make sure you log in to the repository manager using the second link as describe [here])(https://w3c.github.io/repo-transfer.html) to provide enough permissions.

**Comment by lucacasonato** [comment]
Thanks @deniak. I managed to get that far, but the CG is not present in the list of "Relevant groups" under "Community Groups" yet: 
![Screenshot from 2022-05-09 13-29-15](https://user-images.githubusercontent.com/7829205/167401005-86ebc21a-9167-4772-8986-7ec7deece3ca.png)


I think someone needs to add the group using the admin form: https://github.com/w3c/ash-nazg#admin--groups

**Comment by deniak** [comment]
The form will actually list the organizations for which the connected user is admin.
Can you please make sure your ['Authorized OAuth Apps' settings`](https://github.com/settings/applications) lists 'W3C Repository Manager' and that it has access to the `wintercg` organization?

**Comment by lucacasonato** [comment]
Yes, I can see that group in the first dropdown. The issue is that "Web-interoperable Runtimes Community Group" does not show up in the group selector underneath the dropdown (I outlined it in orange):

![image](https://user-images.githubusercontent.com/7829205/167403195-ae82214d-ebd3-429e-b55d-e75da5948bf4.png)

The W3C repo manager is definitely installed on the GitHub org:

![image](https://user-images.githubusercontent.com/7829205/167403368-b5b7450f-ff43-4918-9c7a-0bab7c0c7afe.png)

**Comment by deniak** [comment]
Sorry, I thought the problem was on the list of organizations. I've added the CG to the list and you should now be able to select it while importing your repository.

**Comment by lucacasonato** [comment]
Thanks @deniak! It works now :)
