### ISSUE TITLE
Update repo manager to use WICG/first-party-sets

### ISSUE THREAD

**Issue by krgovind** [w3c/ash-nazg#249]
[First-Party Sets](https://github.com/WICG/first-party-sets/) was recently transferred from PrivacyCG to WICG. Can we generate a new token and update the location repo manager database, please?

IPR bot is failing WICG/first-party-sets/pull/90 with:

`GitHub signature does not match known secret for WICG/first-party-sets.`

Which we previously saw with a similar move/rename in #213. I'm assuming the issue can be fixed as [previously](https://github.com/w3c/ash-nazg/issues/213#issuecomment-908905912) suggested by @deniak .

**Comment by deniak** [comment]
Sorry for the late reply. I've updated the token so upcoming PRs should be no longer fail with that error.
I'll keep that issue open while I investigate why the transfer was not properly processed.

**Comment by deniak** [comment]
Looking at the audit logs of the WICG, I see the repository transited to @cwilso account before ending up under the WICG organization. This is probably why the token wasn't properly updated as the repository manager is not tracking @cwilso's repositories.
