### ISSUE TITLE
Can we rename this thing?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/ash-nazg#25]
Can we please give "ash-nazg" a more obvious name? I can't ever remember what this thing is called and I tend to waste disproportionate amounts of time trying to find it.

**Comment by plehegar** [comment]
Got a proposal? :)

"ipr-checker" ?

or maybe we should run an Internet poll and end up with more flavored names :)

**Comment by marcoscaceres** [comment]
McIPRFace? 😃 

ipr-checker is better. At least easier to remember than what I now call, "ash-gnash-nasty-g"

**Comment by adrianba** [comment]
Checky McCheckFace 😮

**Comment by dontcallmedom** [comment]
are you suggesting changing the name of the [github repo](https://github.com/w3c/ash-nazg) or the name in the [deployed instance](https://labs.w3.org/hatchery/ash-nazg/)? To put it differently, which of the two do you have trouble finding?

**Comment by marcoscaceres** [comment]
The deployed instance. Like, with the WICG, when someone wants a new repo, I need to add it to "gash-nash-smash"... so I end up going to the W3C github org to try to remember what the thing is called and to find the URL (yes, I've never heard of bookmarks either 😄).

**Comment by dontcallmedom** [comment]
it has now moved to https://labs.w3.org/hatchery/repo-manager/
