### ISSUE TITLE
Import w3c/screen-wake-lock

### ISSUE THREAD

**Issue by xfq** [w3c/ash-nazg#252]
We'd like to use repo manager for the [w3c/screen-wake-lock](https://github.com/w3c/screen-wake-lock) repo. I tried using https://labs.w3.org/repo-manager/repo/import , but it emitted `Cannot read properties of undefined (reading 'message')`:

<img width="1235" alt="screen-wake-lock" src="https://user-images.githubusercontent.com/2863444/192973081-68723d85-4551-4f69-8b51-56e5f78abd5d.png">

Here are the errors in the console:

```
Failed to load resource: the server responded with a status of 500 ()
app.js:1 undefined
error @ app.js:1
app.js:1 TypeError: Cannot read properties of undefined (reading 'message')
    at Object.ID_2 (app.js:12:17533)
    at e._invokeCallback (app.js:4:28094)
    at e.dispatch (app.js:4:27896)
    at Object.error (app.js:1:633)
    at app.js:2:29479
error @ app.js:1
```

I'm using Chrome 106. Can anyone point me in the right direction? Thanks!

**Comment by deniak** [comment]
Looking at your screenshot, it seems you have not provided enough rights when login with GH. Can you logout and login again but using the second link (see screenshot below)
<img width="1010" alt="Screen Shot 2022-09-29 at 15 52 14" src="https://user-images.githubusercontent.com/1696128/193024642-1a5fa8c6-6d42-4f3b-89ea-e1599bff709e.png">

**Comment by xfq** [comment]
Thanks for the hint Denis - you are right as usual. Closing.

**Comment by anssiko** [comment]
@xfq @deniak thanks for debugging this. Does the IPR check now work as expected for the w3c/screen-wake-lock repo?

I see two instances of w3c/screen-wake-lock in https://labs.w3.org/repo-manager/repos -- is that intentional?

**Comment by deniak** [comment]
The IPR check should work as expected for w3c/screen-wake-lock.
Looking at the database, I think the duplicate comes from the rename and an additional import.
As the repository manager can now handle repository renaming, it recorded the new name already. But there was another import of the repository that created the second record. I'll clean that up.
