### ISSUE TITLE
When error during import, its message seems lacking

### ISSUE THREAD

**Issue by himorin** [w3c/ash-nazg#257]
When we've tried to import w3c/dapt repository (e.g. https://github.com/w3c/dapt/pull/103#issuecomment-1424587947), a message `e.message is undefined` is shown at the top of [import view](https://labs.w3.org/repo-manager/repo/import).
Also, it seems repository is all set, and I've checked correct selection on import (like de-checking all of 'add'), but it pushes an error. (Actually, I've tried both w3c/dapt and w3c/dapt-reqs.)

![image](https://user-images.githubusercontent.com/3918572/218057473-b1b34d17-c2bf-4b7e-bbbf-d29227257b6b.png)

**Comment by deniak** [comment]
As far as I can see, the repository were not imported in the repository manager.
Can you please make sure you logged in with the right link (cf screenshot) to provide enough permission to import repositories?
<img width="1004" alt="Screenshot 2023-02-10 at 15 52 12" src="https://user-images.githubusercontent.com/1696128/218086394-5660ed8b-a7d1-4d79-b00c-cf273f22de5f.png">

**Comment by himorin** [comment]
how about this capture?

![image](https://user-images.githubusercontent.com/3918572/218095461-90a48596-3982-4eb2-8f28-0edb33631c45.png)

**Comment by himorin** [comment]
Ahh,, thank you for pointing that.
I've failed to check from which I've logged in...
