### ISSUE TITLE
IPR check is not working

### ISSUE THREAD

**Issue by shhnjk** [w3c/ash-nazg#260]
In https://github.com/w3c/webappsec-cspee/pull/28, my PR is blocked by IPR check. However, I'm a member of WebAppSec WG and I have already linked my github account in my W3C account.

I'm not sure what's the problem.

**Comment by shhnjk** [comment]
See https://labs.w3.org/repo-manager/pr/id/w3c/webappsec-cspee/28.

**Comment by deniak** [comment]
The issue came from the fact that your github account was linked to a different W3C account (`jukokats`) affiliated with Microsoft.
I'm guessing you transferred the GH account to a new W3C profile (`shhnjk`).

I've updated the associated account and the IPR check passes now.

**Comment by dveditz** [comment]
Thanks for fixing Jun's account issues!
