### ISSUE TITLE
Creating a new repo or importing message error

### ISSUE THREAD

**Issue by Yonet** [w3c/ash-nazg#266]
When creating or importing a new repository through https://labs.w3.org/repo-manager/repo/new errors with below message. 
Cannot read properties of undefined (reading 'message')

<img width="1076" alt="Screenshot 2024-01-24 at 3 13 02 PM" src="https://github.com/w3c/ash-nazg/assets/3523671/cbf5e8af-41b1-4e12-bb11-5ef3ecf92ff9">
<img width="1063" alt="Screenshot 2024-01-24 at 3 12 30 PM" src="https://github.com/w3c/ash-nazg/assets/3523671/1b2bcf16-28ca-42a1-99ab-b49958020c35">

**Comment by deniak** [comment]
Creating and importing repositories requires more github permissions.

Can you try to logout and login again using the second link from the [login page](https://labs.w3.org/repo-manager/login) (see screenshot below)?

<img width="873" alt="Screenshot 2024-01-24 at 16 22 29" src="https://github.com/w3c/ash-nazg/assets/1696128/5182a3e0-52cf-4062-8142-bb1f463688aa">

**Comment by deniak** [comment]
@Yonet, were you able to import your repository?

**Comment by himorin** [comment]
just note, I've imported to repo manager, and add group configuration to the repo, @Yonet . (feel free to add new at any time)

**Comment by deniak** [comment]
Closing that issue but feel free to re-open it if necessary.

**Comment by Yonet** [comment]
Thank you!
