### ISSUE TITLE
Error when trying to import a repo

### ISSUE THREAD

**Issue by yoavweiss** [w3c/ash-nazg#36]
I'm trying to import the feature-policy repo into the WICG, and the repo-manager (silently) fails to do so.
Looking at the console, I see `app.js:3 Uncaught TypeError: o.default.findDOMNode is not a function`

@dontcallmedom - can you please take a look? Thanks in advance! :)

**Comment by dontcallmedom** [comment]
@tripu this looks likely related to the React upgrade — does the error above ring a bell?

(it's easy to reproduce: go to import repo, pick an org and set whatever repo, hitting the "import" button will silently fail with only the console message as a hint)
