### ISSUE TITLE
For Working Groups, bless people by affiliation's commitment rather than group membership

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/ash-nazg#45]
In WGs, organizations make commitments that encompasses any essential claims that applies in the said specification.

**Comment by dontcallmedom** [comment]
I think the model is:
* if the person is in the WG, ✓
* if the person is not in the WG, but has only one Member-affiliation, and that Member is in the group, ✓
* otherwise, ✗

not sure yet there is an easy way to find if an affiliation is from a Member in the W3C API

**Comment by wseltzer** [comment]
Yes, we need this.

**Comment by plehegar** [comment]
Yoohoo!
