### ISSUE TITLE
Reverting a non-substantive status of a commit

### ISSUE THREAD

**Issue by yoavweiss** [w3c/ash-nazg#54]
https://github.com/WICG/ResizeObserver/pull/27 was accidentally marked as non-substantive, and there's no obvious way to revert it back to substantive status. Is it possible to manually revert it somehow?

**Comment by dontcallmedom** [comment]
I've done the manual revert, and revalidated the PR (which is thus now marked as valid). I'll keep that issue open to offer an admin function to invalidate a PR OK status.

**Comment by SaschaNaz** [comment]
I also accidentally marked https://github.com/WICG/IntersectionObserver/pull/201 as non-substantive, and I'm not sure what it even means. What does 'substantive' mean for the PR?

**Comment by sideshowbarker** [comment]
“substantive” means it is not just an editorial change—for example, just correcting a typo, or rewording some text for clarification, etc.—but is instead a change the to normative requirements in the spec; for example, something that would require implementors to change their implementations
