### ISSUE TITLE
Error importing wicg "scroll-animations"

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/ash-nazg#57]
When importing the repository "scroll-animations" from WICG, I get the following error from the ash-nazg interface:

```JS
JSON Parse error: Unexpected identifier "TypeError"
```

The repo is here:
https://github.com/WICG/scroll-animations

**Comment by dontcallmedom** [comment]
hmm... just imported it without error, so could not reproduce the bug.

Was there anything more in the console by any chance?

**Comment by marcoscaceres** [comment]
Sorry, no. I forgot to check the Dev console as the error was shown on the page in an error toast (so I assumed this was the server-side issue). Glad it started working again tho.
