### ISSUE TITLE
ash-nazg should handle repository name changes

### ISSUE THREAD

**Issue by plehegar** [w3c/ash-nazg#64]
https://labs.w3.org/hatchery/repo-manager/pr/id/w3c/webpayments-core-messages/5

doesn't do anything when one tries to mark this PR as non-substantive. Note that the PR author doesn't appear as contributor in ash-nazg.

**Comment by plehegar** [comment]
This PR is at https://github.com/w3c/webpayments-http-messages/pull/5

**Comment by dontcallmedom** [comment]
So the problem arises because the repository was moved (i.e. had its name changed), and ash-nazg doesn't handle this gracefully at the moment. Renaming the issue accordingly.

**Comment by dontcallmedom** [comment]
there doesn't seem to be an event in the GH API when a repo is moved at the moment, although it [seems to be on the "wishlist"](https://platform.github.community/t/not-being-redirected-when-organization-is-renamed/2159/2).

A possible fallback solution in the meantime would be:
* to add a UI to a repo to reflect its new name (possibly new owner as well)
* to notify repo contacts when an event is received for a repo whose name doesn't match what we expect (not sure it can be done though)

**Comment by dontcallmedom** [comment]
Among other things that would need to be handled when a repo is transfered is ensuring the existing tracked open pull requests be re-associated to the new owner, associated with the right groups, and be re-validated accordingly.

**Comment by plehegar** [comment]
looking at the GH API feedback, it looks like the redirect will now happen properly but still no event. We could revalidate the repositories known to ash-nazg and detect the renaming at least.

**Comment by deniak** [comment]
Each GH repository actually have an ID which we can rely on and will work after a rename but this could require a bit of work as ash-nazg currently heavily relies on the 'owner/shortname' of the repo

**Comment by dontcallmedom** [comment]
the rename event didn't exist back when this issue was raised - I agree that it sounds like the right approach.

**Comment by plehegar** [comment]
I'm ok ok either, whatever is the easiest to implement. I'm not worried about missing PR within 24 hours or less of a move.
