### ISSUE TITLE
Automatic notification for failed IPR checks is poorly documented

### ISSUE THREAD

**Issue by chaals** [w3c/ash-nazg#70]
Hi,

in some groups there are a large number of repos, and a small number of people dealing with them.

It would be really helpful if I could set a repo to automatically notify me when an IPR check is failed so I go look at the problem…

**Comment by dontcallmedom** [comment]
this is already possible by adding your github login to the contacts field in w3c.json at the top of the repo. see also https://github.com/w3c/ash-nazg/issues/27

**Comment by chaals** [comment]
Is this written down anywhere else but here?

What does it actually mean to put my name into the w3c.json?

What does that file do?

How do I find out from the ash-nazg tool interface, which is where I arrive when a contribution fails an IPR check.
