### ISSUE TITLE
Improve contribution flow & documentation

### ISSUE THREAD

**Issue by scheib** [w3c/ash-nazg#71]
1) Be an active W3C member and contributor
2) Submit a pull request, e.g. https://github.com/w3c/mediacapture-image/pull/173
3) Have 'ipr' [trigger a failure](http://pasteboard.co/1vT6XQJko.png) with a [details link](http://pasteboard.co/1vSjPPu7C.png) requiring a login / and [authorizing many permissions](http://pasteboard.co/1vUR4JhSi.png).

Expect: 

- Actionable summary of how to correctly register contributor status. And, ability to do so.

Actual:

- Details are not provided, just a log in page with text that indicates significant permissions are required without justifying them.

> 
> This site is essentially an application built on top of GitHub. As such, in order for it to work, you need to log into it using your GitHub credentials.
> 
> Given that the actions we need to carry out are fairly extensive, the level of permissions we require is relatively high. Worry not, we promise to almost never use it for anything evil.
> 
> Go ahead and log in using GitHub.
> 

- Permissions requested by this app are overly broad, including **read and write all public repository data**.

Suggestion: 

- Explain in the details page what the IPR validation is.
- Explain steps to correctly register.
- Do not require overly broad account permissions to do so.

**Comment by dontcallmedom** [comment]
you're absolutely right - that's something that has bothered me a number of times, but which I tend to forget since I'm logged in most of the time. This will become even more critical as we expect the tool to expand in its usage, so I'll try to fix this sooner rather than later.

**Comment by dontcallmedom** [comment]
Closing this now - documentation has been improved; pages that could be made public (incl the PR details view) have been made so.

There is still some work to request fewer permissions by default but I'm tracking this in #44.
