### ISSUE TITLE
Issue: undefined is not an object (evaluating 'e.pr.groupDetails[0].groupType')

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/ash-nazg#72]
When accessing:
https://labs.w3.org/hatchery/repo-manager/pr/id/w3c/browser-payment-api/525

I am getting: 
"undefined is not an object (evaluating 'e.pr.groupDetails[0].groupType')"

In both Chrome and Safari: 
![screenshot 2017-05-08 18 46 10](https://cloud.githubusercontent.com/assets/870154/25796929/b62a17d6-341e-11e7-8ee4-13e427a63b60.png)

**Comment by dontcallmedom** [comment]
fixed thanks the report
