### ISSUE TITLE
Wrong redirect after logging in

### ISSUE THREAD

**Issue by tripu** [w3c/ash-nazg#91]
Both on [`labs.w3.org/hatchery/repo-manager`](https://labs.w3.org/hatchery/repo-manager/) and on my local instance, when I log in successfully using GH, I end up on `/login` with a message &ldquo;Cannot GET /login&rdquo;.

I see this chain of redirects:

1. `https://labs.w3.org/hatchery/hatchery/repo-manager/login` (`/hatchery/hatchery/`)  
  :large_orange_diamond: `301` `Moved Permanently` &rarr; `http://labs.w3.org/hatchery/repo-manager/login`
1. `http://labs.w3.org/hatchery/repo-manager/login` (HTTP)  
  :large_orange_diamond: `307` `Internal Redirect` &rarr; `https://labs.w3.org/hatchery/repo-manager/login`
1. `https://labs.w3.org/hatchery/repo-manager/login` (HTTP + SSL)  
  :red_circle: `404` `Not Found`

I thought [HTTPS Everywhere](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp) might be messing with URLs, but I just disabled it and tried again, with the same result.

**Comment by marcoscaceres** [comment]
This I happening again:
```
Cannot GET /hatchery/repo-manager/repo-manager/login
```

**Comment by plehegar** [comment]
confirmed. This seems broken.

**Comment by plehegar** [comment]
note that if you do go back to https://labs.w3.org/hatchery/repo-manager/login , you do get logged back at some point.

**Comment by tripu** [comment]
I did some tests in a couple occasions, but still don't understand if this is caused by Ash-Nazg (bad) routing, or by our reverse proxy rules.

**Comment by deniak** [comment]
There was an issue with the front-end proxy and @ylafon managed to fix it. It should now work as expected.

**Comment by tripu** [comment]
Thank you, @ylafon &amp; @deniak!
