### ISSUE TITLE
Tie repository creation/import to suggestions and templates for WG home pages

### ISSUE THREAD

**Issue by tripu** [w3c/ash-nazg#98]
More an idea and a note-to-self than an issue.

As part of our effort to streamline WG creation and administration and to normalise the appearance of WG home pages (see projects [Unitas](https://github.com/w3c/Unitas), [Apiary](https://github.com/w3c/apiary)), it may be useful to help bootstrap home pages for new WGs at the stage where many groups start: using Ash-Nazg to create a repository for their first spec.

When [creating](https://labs.w3.org/hatchery/repo-manager/repo/new) or [importing](https://labs.w3.org/hatchery/repo-manager/repo/import) a new repo, Ash-Nazg could suggest the creation of *another* repository to hold the WG's main web page. If the user agrees, Ash-Nazg would create that other repo starting from a template (similar to what we do with the spec repo itself at the moment). As of writing, the emerging way to quickly have a WG web page is by recycling the [Web Performance WG](https://www.w3.org/webperf/) / [Verifiable Claims WG](https://www.w3.org/2017/vc/WG/) &ldquo;template&rdquo; and extending it with a bit of [Apiary](https://github.com/w3c/apiary) to populate it with dynamic data.

After that is done, a flag in Ash-Nazg DB will indicate that we don't need to prompt members of that WG for the same operation again in the future even if they use Ash-Nazg to create/import new spec repos. The same flag will be set if the user responds by ticking the option *&ldquo;we are an old group and have a page already; don't bother us with that again&rdquo;* instead.

Ash-Nazg will need to handle a bit or two of new metadata about WGs for this, but much of the logic will be similar to what we have now, and could be refactored (interaction with GH API to create a new repo and add some standard files to it, with specific values instead of placeholders, etc).

@koalie, @dontcallmedom: WDYT?

**Comment by dontcallmedom** [comment]
I think the idea of facilitating the adoption of a WG home page template (and maybe more generally, WG home page set up) is a good one; but I feel pretty strongly ash-nazg is not the right place for this:
* ash-nazg itself is not yet so widely adopted that groups would go there first and foremost
* ash-nazg only gets into play once people have repos - new WGs need home pages well before that

**Comment by tripu** [comment]
@dontcallmedom, I see what you mean.

Can you think of another tool, event or check box around the time a new WG is created, to which we could hook up this logic? I'm basically interested in making this easy for groups, and rely less on a human remembering to tell another human &ldquo;oh, and you should use that template over there in this way to create the WG home page&rdquo;&hellip;

**Comment by koalie** [comment]
I defer/concur/abstain on the issue, being unfamiliar with ash-nazg itself and the workflow it involves.

I support streamlining WG creation and administration and normalising the appearance of WG home pages.
